-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.catalogo_logros
(
    id_catalogo_logro integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    clave character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(200) COLLATE pg_catalog."default",
    icono character varying(50) COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT catalogo_logros_pkey PRIMARY KEY (id_catalogo_logro),
    CONSTRAINT catalogo_logros_clave_key UNIQUE (clave)
);

CREATE TABLE IF NOT EXISTS public.estadisticas_habilidad
(
    id_estadistica integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    estudiante_id integer NOT NULL,
    habilidad_id integer NOT NULL,
    total_intentos integer NOT NULL DEFAULT 0,
    aciertos integer NOT NULL DEFAULT 0,
    errores integer NOT NULL DEFAULT 0,
    precision_pct numeric(5, 2) NOT NULL DEFAULT 0.00,
    promedio_reaccion_ms integer,
    actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT estadisticas_habilidad_pkey PRIMARY KEY (id_estadistica),
    CONSTRAINT estadisticas_habilidad_estudiante_id_habilidad_id_key UNIQUE (estudiante_id, habilidad_id)
);

CREATE TABLE IF NOT EXISTS public.estados_estudiante
(
    id_estado_estudiante integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estados_estudiante_pkey PRIMARY KEY (id_estado_estudiante),
    CONSTRAINT estados_estudiante_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.estados_sesion
(
    id_estado_sesion integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estados_sesion_pkey PRIMARY KEY (id_estado_sesion),
    CONSTRAINT estados_sesion_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.estados_usuario
(
    id_estado_usuario integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estados_usuario_pkey PRIMARY KEY (id_estado_usuario),
    CONSTRAINT estados_usuario_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.estudiante_grupo_historial
(
    id_est_grupo integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    estudiante_id integer NOT NULL,
    grupo_id integer NOT NULL,
    fecha_inicio date NOT NULL DEFAULT CURRENT_DATE,
    fecha_fin date,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT estudiante_grupo_historial_pkey PRIMARY KEY (id_est_grupo),
    CONSTRAINT estudiante_grupo_historial_estudiante_id_grupo_id_fecha_ini_key UNIQUE (estudiante_id, grupo_id, fecha_inicio)
);

CREATE TABLE IF NOT EXISTS public.estudiantes
(
    id_estudiante integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    edad integer NOT NULL,
    color_avatar character varying(7) COLLATE pg_catalog."default" NOT NULL DEFAULT '#3B82F6'::character varying,
    qr_token character varying(120) COLLATE pg_catalog."default" NOT NULL,
    sesion_activa boolean NOT NULL DEFAULT false,
    estado_id integer NOT NULL DEFAULT 1,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
    institucion_id integer,
    CONSTRAINT estudiantes_pkey PRIMARY KEY (id_estudiante),
    CONSTRAINT estudiantes_qr_token_key UNIQUE (qr_token)
);

CREATE TABLE IF NOT EXISTS public.eventos_sesion
(
    id_evento_sesion integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    sesion_id integer NOT NULL,
    tipo_evento_id integer NOT NULL,
    habilidad_id integer,
    tiempo_reaccion_ms integer,
    puntos integer NOT NULL DEFAULT 0,
    combo_en_evento integer NOT NULL DEFAULT 0,
    ocurrido_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT eventos_sesion_pkey PRIMARY KEY (id_evento_sesion)
);

CREATE TABLE IF NOT EXISTS public.grupos
(
    id_grupo integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    usuario_id integer NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    predeterminado boolean NOT NULL DEFAULT false,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
    institucion_id integer,
    CONSTRAINT grupos_pkey PRIMARY KEY (id_grupo),
    CONSTRAINT grupos_usuario_id_nombre_key UNIQUE (usuario_id, nombre)
);

CREATE TABLE IF NOT EXISTS public.habilidades
(
    id_habilidad integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT habilidades_pkey PRIMARY KEY (id_habilidad),
    CONSTRAINT habilidades_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.instituciones
(
    id_institucion integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    ciudad character varying(100) COLLATE pg_catalog."default",
    direccion character varying(200) COLLATE pg_catalog."default",
    telefono character varying(30) COLLATE pg_catalog."default",
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT instituciones_pkey PRIMARY KEY (id_institucion),
    CONSTRAINT instituciones_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.logros
(
    id_logro integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    estudiante_id integer NOT NULL,
    catalogo_logro_id integer NOT NULL,
    desbloqueado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT logros_pkey PRIMARY KEY (id_logro),
    CONSTRAINT logros_estudiante_id_catalogo_logro_id_key UNIQUE (estudiante_id, catalogo_logro_id)
);

CREATE TABLE IF NOT EXISTS public.minijuegos
(
    id_minijuego integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    slug character varying(50) COLLATE pg_catalog."default" NOT NULL,
    titulo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    habilidad_id integer NOT NULL,
    dificultad_maxima integer NOT NULL DEFAULT 4,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT minijuegos_pkey PRIMARY KEY (id_minijuego),
    CONSTRAINT minijuegos_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.modelos_ia
(
    id_modelo_ia integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    proveedor character varying(50) COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT modelos_ia_pkey PRIMARY KEY (id_modelo_ia),
    CONSTRAINT modelos_ia_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.niveles_severidad
(
    id_nivel_severidad integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT niveles_severidad_pkey PRIMARY KEY (id_nivel_severidad),
    CONSTRAINT niveles_severidad_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.recomendaciones
(
    id_recomendacion integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    estudiante_id integer,
    grupo_id integer,
    habilidad_id integer,
    severidad_id integer NOT NULL DEFAULT 2,
    modelo_ia_id integer,
    mensaje text COLLATE pg_catalog."default" NOT NULL,
    precision_momento numeric(5, 2),
    generado_en timestamp with time zone NOT NULL DEFAULT now(),
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT recomendaciones_pkey PRIMARY KEY (id_recomendacion)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id_rol integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(150) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id_rol),
    CONSTRAINT roles_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.sesiones_juego
(
    id_sesion_juego integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    estudiante_id integer NOT NULL,
    minijuego_id integer NOT NULL,
    dificultad integer NOT NULL,
    puntaje integer NOT NULL DEFAULT 0,
    aciertos integer NOT NULL DEFAULT 0,
    errores integer NOT NULL DEFAULT 0,
    combo_maximo integer NOT NULL DEFAULT 0,
    estado_id integer NOT NULL DEFAULT 1,
    iniciada_en timestamp with time zone NOT NULL DEFAULT now(),
    finalizada_en timestamp with time zone,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT sesiones_juego_pkey PRIMARY KEY (id_sesion_juego)
);

CREATE TABLE IF NOT EXISTS public.tipos_evento
(
    id_tipo_evento integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tipos_evento_pkey PRIMARY KEY (id_tipo_evento),
    CONSTRAINT tipos_evento_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id_usuario integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    contrasena_hash text COLLATE pg_catalog."default" NOT NULL,
    rol_id integer NOT NULL,
    institucion_id integer,
    estado_id integer NOT NULL DEFAULT 1,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT usuarios_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.estadisticas_habilidad
    ADD CONSTRAINT estadisticas_habilidad_estudiante_id_fkey FOREIGN KEY (estudiante_id)
    REFERENCES public.estudiantes (id_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_estadisticas_estudiante
    ON public.estadisticas_habilidad(estudiante_id);


ALTER TABLE IF EXISTS public.estadisticas_habilidad
    ADD CONSTRAINT estadisticas_habilidad_habilidad_id_fkey FOREIGN KEY (habilidad_id)
    REFERENCES public.habilidades (id_habilidad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_estadisticas_habilidad
    ON public.estadisticas_habilidad(habilidad_id);


ALTER TABLE IF EXISTS public.estudiante_grupo_historial
    ADD CONSTRAINT estudiante_grupo_historial_estudiante_id_fkey FOREIGN KEY (estudiante_id)
    REFERENCES public.estudiantes (id_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ux_est_un_grupo_activo
    ON public.estudiante_grupo_historial(estudiante_id);


ALTER TABLE IF EXISTS public.estudiante_grupo_historial
    ADD CONSTRAINT estudiante_grupo_historial_grupo_id_fkey FOREIGN KEY (grupo_id)
    REFERENCES public.grupos (id_grupo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_egh_grupo
    ON public.estudiante_grupo_historial(grupo_id);


ALTER TABLE IF EXISTS public.estudiantes
    ADD CONSTRAINT estudiantes_estado_id_fkey FOREIGN KEY (estado_id)
    REFERENCES public.estados_estudiante (id_estado_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_estudiantes_estado
    ON public.estudiantes(estado_id);


ALTER TABLE IF EXISTS public.estudiantes
    ADD CONSTRAINT estudiantes_institucion_id_fkey FOREIGN KEY (institucion_id)
    REFERENCES public.instituciones (id_institucion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.eventos_sesion
    ADD CONSTRAINT eventos_sesion_habilidad_id_fkey FOREIGN KEY (habilidad_id)
    REFERENCES public.habilidades (id_habilidad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_eventos_habilidad
    ON public.eventos_sesion(habilidad_id);


ALTER TABLE IF EXISTS public.eventos_sesion
    ADD CONSTRAINT eventos_sesion_sesion_id_fkey FOREIGN KEY (sesion_id)
    REFERENCES public.sesiones_juego (id_sesion_juego) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_eventos_sesion
    ON public.eventos_sesion(sesion_id);


ALTER TABLE IF EXISTS public.eventos_sesion
    ADD CONSTRAINT eventos_sesion_tipo_evento_id_fkey FOREIGN KEY (tipo_evento_id)
    REFERENCES public.tipos_evento (id_tipo_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_eventos_tipo
    ON public.eventos_sesion(tipo_evento_id);


ALTER TABLE IF EXISTS public.grupos
    ADD CONSTRAINT grupos_institucion_id_fkey FOREIGN KEY (institucion_id)
    REFERENCES public.instituciones (id_institucion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.grupos
    ADD CONSTRAINT grupos_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_grupos_usuario
    ON public.grupos(usuario_id);


ALTER TABLE IF EXISTS public.logros
    ADD CONSTRAINT logros_catalogo_logro_id_fkey FOREIGN KEY (catalogo_logro_id)
    REFERENCES public.catalogo_logros (id_catalogo_logro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_logros_catalogo
    ON public.logros(catalogo_logro_id);


ALTER TABLE IF EXISTS public.logros
    ADD CONSTRAINT logros_estudiante_id_fkey FOREIGN KEY (estudiante_id)
    REFERENCES public.estudiantes (id_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_logros_estudiante
    ON public.logros(estudiante_id);


ALTER TABLE IF EXISTS public.minijuegos
    ADD CONSTRAINT minijuegos_habilidad_id_fkey FOREIGN KEY (habilidad_id)
    REFERENCES public.habilidades (id_habilidad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_minijuegos_habilidad
    ON public.minijuegos(habilidad_id);


ALTER TABLE IF EXISTS public.recomendaciones
    ADD CONSTRAINT recomendaciones_estudiante_id_fkey FOREIGN KEY (estudiante_id)
    REFERENCES public.estudiantes (id_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rec_estudiante
    ON public.recomendaciones(estudiante_id);


ALTER TABLE IF EXISTS public.recomendaciones
    ADD CONSTRAINT recomendaciones_grupo_id_fkey FOREIGN KEY (grupo_id)
    REFERENCES public.grupos (id_grupo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rec_grupo
    ON public.recomendaciones(grupo_id);


ALTER TABLE IF EXISTS public.recomendaciones
    ADD CONSTRAINT recomendaciones_habilidad_id_fkey FOREIGN KEY (habilidad_id)
    REFERENCES public.habilidades (id_habilidad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.recomendaciones
    ADD CONSTRAINT recomendaciones_modelo_ia_id_fkey FOREIGN KEY (modelo_ia_id)
    REFERENCES public.modelos_ia (id_modelo_ia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_rec_modelo
    ON public.recomendaciones(modelo_ia_id);


ALTER TABLE IF EXISTS public.recomendaciones
    ADD CONSTRAINT recomendaciones_severidad_id_fkey FOREIGN KEY (severidad_id)
    REFERENCES public.niveles_severidad (id_nivel_severidad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_rec_severidad
    ON public.recomendaciones(severidad_id);


ALTER TABLE IF EXISTS public.sesiones_juego
    ADD CONSTRAINT sesiones_juego_estado_id_fkey FOREIGN KEY (estado_id)
    REFERENCES public.estados_sesion (id_estado_sesion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_sesiones_estado
    ON public.sesiones_juego(estado_id);


ALTER TABLE IF EXISTS public.sesiones_juego
    ADD CONSTRAINT sesiones_juego_estudiante_id_fkey FOREIGN KEY (estudiante_id)
    REFERENCES public.estudiantes (id_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sesiones_estudiante
    ON public.sesiones_juego(estudiante_id);


ALTER TABLE IF EXISTS public.sesiones_juego
    ADD CONSTRAINT sesiones_juego_minijuego_id_fkey FOREIGN KEY (minijuego_id)
    REFERENCES public.minijuegos (id_minijuego) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_sesiones_minijuego
    ON public.sesiones_juego(minijuego_id);


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_estado_id_fkey FOREIGN KEY (estado_id)
    REFERENCES public.estados_usuario (id_estado_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_usuarios_estado
    ON public.usuarios(estado_id);


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_institucion_id_fkey FOREIGN KEY (institucion_id)
    REFERENCES public.instituciones (id_institucion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_usuarios_institucion
    ON public.usuarios(institucion_id);


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_rol_id_fkey FOREIGN KEY (rol_id)
    REFERENCES public.roles (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_usuarios_rol
    ON public.usuarios(rol_id);

END;
