-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.catalogo_logros
(
    id_catalogo_logro integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    clave character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(200) COLLATE pg_catalog."default",
    icono character varying(50) COLLATE pg_catalog."default",
    tipo character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'global',
    modulo character varying(20) COLLATE pg_catalog."default",
    icon_key character varying(80) COLLATE pg_catalog."default",
    puntos integer NOT NULL DEFAULT 1,
    condicion_desbloqueo jsonb NOT NULL DEFAULT '{}'::jsonb,
    orden integer NOT NULL DEFAULT 100,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT catalogo_logros_pkey PRIMARY KEY (id_catalogo_logro),
    CONSTRAINT catalogo_logros_clave_key UNIQUE (clave),
    CONSTRAINT ck_catalogo_logros_tipo CHECK (tipo::text = ANY (ARRAY['module'::character varying, 'global'::character varying, 'special'::character varying]::text[])),
    CONSTRAINT ck_catalogo_logros_modulo CHECK (modulo IS NULL OR modulo::text = ANY (ARRAY['memoria'::character varying, 'patrones'::character varying, 'logica'::character varying, 'razonar'::character varying, 'atencion'::character varying]::text[]))
);

CREATE TABLE IF NOT EXISTS public.estadisticas_habilidad
(
    id_estadistica integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    estudiante_id integer NOT NULL,
    habilidad_id integer NOT NULL,
    total_intentos integer NOT NULL DEFAULT 0,
    aciertos integer NOT NULL DEFAULT 0,
    errores integer NOT NULL DEFAULT 0,
    precision_pct numeric(5, 2) NOT NULL DEFAULT 0.00,
    promedio_reaccion_ms integer,
    actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT estadisticas_habilidad_pkey PRIMARY KEY (id_estadistica),
    CONSTRAINT estadisticas_habilidad_estudiante_id_habilidad_id_key UNIQUE (estudiante_id, habilidad_id)
);

CREATE TABLE IF NOT EXISTS public.estados_estudiante
(
    id_estado_estudiante integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estados_estudiante_pkey PRIMARY KEY (id_estado_estudiante),
    CONSTRAINT estados_estudiante_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.estados_sesion
(
    id_estado_sesion integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estados_sesion_pkey PRIMARY KEY (id_estado_sesion),
    CONSTRAINT estados_sesion_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.estados_usuario
(
    id_estado_usuario integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estados_usuario_pkey PRIMARY KEY (id_estado_usuario),
    CONSTRAINT estados_usuario_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.estudiante_grupo_historial
(
    id_est_grupo integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    estudiante_id integer NOT NULL,
    grupo_id integer NOT NULL,
    fecha_inicio date NOT NULL DEFAULT CURRENT_DATE,
    fecha_fin date,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT estudiante_grupo_historial_pkey PRIMARY KEY (id_est_grupo),
    CONSTRAINT estudiante_grupo_historial_estudiante_id_grupo_id_fecha_ini_key UNIQUE (estudiante_id, grupo_id, fecha_inicio)
);

CREATE TABLE IF NOT EXISTS public.grupo_tutor_historial
(
    id_grupo_tutor integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grupo_id integer NOT NULL,
    tutor_id integer NOT NULL,
    asignado_por integer NOT NULL,
    fecha_inicio timestamp with time zone NOT NULL DEFAULT now(),
    fecha_fin timestamp with time zone,
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT grupo_tutor_historial_pkey PRIMARY KEY (id_grupo_tutor),
    CONSTRAINT grupo_tutor_historial_grupo_id_tutor_id_fecha_ini_key UNIQUE (grupo_id, tutor_id, fecha_inicio)
);

CREATE TABLE IF NOT EXISTS public.estudiantes
(
    id_estudiante integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    edad integer NOT NULL,
    color_avatar character varying(7) COLLATE pg_catalog."default" NOT NULL DEFAULT '#3B82F6'::character varying,
    qr_token character varying(120) COLLATE pg_catalog."default" NOT NULL,
    estado_id integer NOT NULL DEFAULT 1,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
    institucion_id integer,
    CONSTRAINT estudiantes_pkey PRIMARY KEY (id_estudiante),
    CONSTRAINT estudiantes_qr_token_key UNIQUE (qr_token)
);

CREATE TABLE IF NOT EXISTS public.eventos_sesion
(
    id_evento_sesion integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    sesion_id integer NOT NULL,
    tipo_evento_id integer NOT NULL,
    habilidad_id integer,
    tiempo_reaccion_ms integer,
    puntos integer NOT NULL DEFAULT 0,
    combo_en_evento integer NOT NULL DEFAULT 0,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    ocurrido_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT eventos_sesion_pkey PRIMARY KEY (id_evento_sesion)
);

CREATE TABLE IF NOT EXISTS public.grupos
(
    id_grupo integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    creado_por_usuario_id integer NOT NULL,
    tutor_asignado_id integer,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    predeterminado boolean NOT NULL DEFAULT false,
    activo boolean NOT NULL DEFAULT true,
    archivado_en timestamp with time zone,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
    institucion_id integer,
    CONSTRAINT grupos_pkey PRIMARY KEY (id_grupo),
    CONSTRAINT ck_grupos_estado_consistente CHECK (
        (activo = true AND archivado_en IS NULL) OR
        (activo = false AND archivado_en IS NOT NULL)
    ),
    CONSTRAINT grupos_institucion_id_nombre_key UNIQUE (institucion_id, nombre)
);

CREATE TABLE IF NOT EXISTS public.habilidades
(
    id_habilidad integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT habilidades_pkey PRIMARY KEY (id_habilidad),
    CONSTRAINT habilidades_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.instituciones
(
    id_institucion integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    ciudad character varying(100) COLLATE pg_catalog."default",
    direccion character varying(200) COLLATE pg_catalog."default",
    telefono character varying(30) COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    desactivado_en timestamp with time zone,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT instituciones_pkey PRIMARY KEY (id_institucion),
    CONSTRAINT ck_instituciones_estado_consistente CHECK (
        (activo = true AND desactivado_en IS NULL) OR
        (activo = false AND desactivado_en IS NOT NULL)
    ),
    CONSTRAINT instituciones_nombre_key UNIQUE (nombre)
);
CREATE INDEX IF NOT EXISTS idx_instituciones_activo
    ON public.instituciones(activo);

CREATE TABLE IF NOT EXISTS public.logros
(
    id_logro integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    estudiante_id integer NOT NULL,
    catalogo_logro_id integer NOT NULL,
    desbloqueado_en timestamp with time zone NOT NULL DEFAULT now(),
    sesion_id integer,
    puntos_otorgados integer NOT NULL DEFAULT 0,
    CONSTRAINT logros_pkey PRIMARY KEY (id_logro),
    CONSTRAINT logros_estudiante_id_catalogo_logro_id_key UNIQUE (estudiante_id, catalogo_logro_id)
);

CREATE TABLE IF NOT EXISTS public.minijuegos
(
    id_minijuego integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    slug character varying(50) COLLATE pg_catalog."default" NOT NULL,
    titulo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    habilidad_id integer NOT NULL,
    dificultad_maxima integer NOT NULL DEFAULT 4,
    activo boolean NOT NULL DEFAULT true,
    visible_en_catalogo boolean NOT NULL DEFAULT true,
    orden_catalogo integer NOT NULL DEFAULT 100,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT minijuegos_pkey PRIMARY KEY (id_minijuego),
    CONSTRAINT minijuegos_slug_key UNIQUE (slug),
    CONSTRAINT ck_minijuegos_orden_catalogo CHECK (orden_catalogo > 0)
);

CREATE TABLE IF NOT EXISTS public.modelos_ia
(
    id_modelo_ia integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    proveedor character varying(50) COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT modelos_ia_pkey PRIMARY KEY (id_modelo_ia),
    CONSTRAINT modelos_ia_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.niveles_severidad
(
    id_nivel_severidad integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT niveles_severidad_pkey PRIMARY KEY (id_nivel_severidad),
    CONSTRAINT niveles_severidad_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.recomendaciones
(
    id_recomendacion integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    estudiante_id integer,
    grupo_id integer,
    habilidad_id integer,
    severidad_id integer NOT NULL DEFAULT 2,
    modelo_ia_id integer,
    mensaje text COLLATE pg_catalog."default" NOT NULL,
    precision_momento numeric(5, 2),
    origen_generacion character varying(20) NOT NULL DEFAULT 'legacy',
    version_reglas character varying(30),
    input_snapshot_json jsonb,
    generado_en timestamp with time zone NOT NULL DEFAULT now(),
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT recomendaciones_pkey PRIMARY KEY (id_recomendacion),
    CONSTRAINT ck_recomendaciones_origen CHECK (origen_generacion IN ('legacy', 'plantilla', 'dataset', 'gemini', 'fallback')),
    CONSTRAINT ck_recomendaciones_destino CHECK ((estudiante_id IS NULL) <> (grupo_id IS NULL))
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id_rol integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(150) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id_rol),
    CONSTRAINT roles_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.rutas_pedagogicas
(
    id_ruta_pedagogica integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    slug character varying(60) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(120) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    visible_en_catalogo boolean NOT NULL DEFAULT true,
    orden_catalogo integer NOT NULL DEFAULT 100,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT rutas_pedagogicas_pkey PRIMARY KEY (id_ruta_pedagogica),
    CONSTRAINT rutas_pedagogicas_slug_key UNIQUE (slug),
    CONSTRAINT ck_rutas_pedagogicas_orden_catalogo CHECK (orden_catalogo > 0)
);

CREATE TABLE IF NOT EXISTS public.ruta_pedagogica_bloques
(
    id_ruta_pedagogica_bloque integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ruta_pedagogica_id integer NOT NULL,
    orden integer NOT NULL,
    minijuego_id integer NOT NULL,
    niveles integer NOT NULL DEFAULT 1,
    configuracion_base jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT ruta_pedagogica_bloques_pkey PRIMARY KEY (id_ruta_pedagogica_bloque),
    CONSTRAINT ck_ruta_pedagogica_bloques_orden CHECK (orden > 0),
    CONSTRAINT ck_ruta_pedagogica_bloques_niveles CHECK (niveles > 0),
    CONSTRAINT uq_ruta_pedagogica_bloques_orden UNIQUE (ruta_pedagogica_id, orden)
);

CREATE TABLE IF NOT EXISTS public.sesiones_clase
(
    id_sesion_clase integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grupo_id integer NOT NULL,
    tutor_responsable_id integer NOT NULL,
    abierta_por_usuario_id integer NOT NULL,
    ruta_pedagogica_id integer,
    modo character varying(20) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'activa'::character varying,
    abierta_en timestamp with time zone NOT NULL DEFAULT now(),
    cerrada_en timestamp with time zone,
    cierre_motivo character varying(30) COLLATE pg_catalog."default",
    actualizada_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT sesiones_clase_pkey PRIMARY KEY (id_sesion_clase),
    CONSTRAINT ck_sesiones_clase_modo CHECK (modo::text = ANY (ARRAY['single'::character varying, 'path'::character varying]::text[])),
    CONSTRAINT ck_sesiones_clase_estado CHECK (estado::text = ANY (ARRAY['activa'::character varying, 'cerrada'::character varying, 'cancelada'::character varying]::text[])),
    CONSTRAINT ck_sesiones_clase_consistente CHECK (
        (estado::text = 'activa'::text AND cerrada_en IS NULL AND cierre_motivo IS NULL) OR
        (estado::text = ANY (ARRAY['cerrada'::character varying, 'cancelada'::character varying]::text[]) AND cerrada_en IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS public.sesion_clase_pasos
(
    id_sesion_clase_paso integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    sesion_clase_id integer NOT NULL,
    orden integer NOT NULL,
    bloque_orden integer NOT NULL DEFAULT 1,
    nivel_en_bloque integer NOT NULL DEFAULT 1,
    minijuego_id integer NOT NULL,
    configuracion_base jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT sesion_clase_pasos_pkey PRIMARY KEY (id_sesion_clase_paso),
    CONSTRAINT ck_sesion_clase_pasos_orden CHECK (orden > 0),
    CONSTRAINT ck_sesion_clase_pasos_bloque_orden CHECK (bloque_orden > 0),
    CONSTRAINT ck_sesion_clase_pasos_nivel_en_bloque CHECK (nivel_en_bloque > 0),
    CONSTRAINT uq_sesion_clase_pasos_orden UNIQUE (sesion_clase_id, orden)
);

CREATE TABLE IF NOT EXISTS public.sesion_clase_participantes
(
    id_sesion_clase_participante integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    sesion_clase_id integer NOT NULL,
    estudiante_id integer NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pendiente'::character varying,
    paso_actual integer NOT NULL DEFAULT 1,
    iniciada_en timestamp with time zone,
    finalizada_en timestamp with time zone,
    CONSTRAINT sesion_clase_participantes_pkey PRIMARY KEY (id_sesion_clase_participante),
    CONSTRAINT ck_sesion_clase_participantes_estado CHECK (
        estado::text = ANY (ARRAY['pendiente'::character varying, 'en_progreso'::character varying, 'completado'::character varying, 'abandonado'::character varying, 'cerrado'::character varying]::text[])
    ),
    CONSTRAINT ck_sesion_clase_participantes_paso CHECK (paso_actual > 0),
    CONSTRAINT uq_sesion_clase_participante UNIQUE (sesion_clase_id, estudiante_id)
);

CREATE TABLE IF NOT EXISTS public.sesiones_juego
(
    id_sesion_juego integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    estudiante_id integer NOT NULL,
    minijuego_id integer NOT NULL,
    dificultad integer NOT NULL,
    puntaje integer NOT NULL DEFAULT 0,
    aciertos integer NOT NULL DEFAULT 0,
    errores integer NOT NULL DEFAULT 0,
    combo_maximo integer NOT NULL DEFAULT 0,
    estrellas_obtenidas integer NOT NULL DEFAULT 0,
    estado_id integer NOT NULL DEFAULT 1,
    sesion_clase_id integer,
    orden_en_ruta integer NOT NULL DEFAULT 1,
    configuracion_aplicada jsonb NOT NULL DEFAULT '{}'::jsonb,
    fuente_adaptacion character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'base'::character varying,
    modelo_ia_id integer,
    iniciada_en timestamp with time zone NOT NULL DEFAULT now(),
    finalizada_en timestamp with time zone,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT sesiones_juego_pkey PRIMARY KEY (id_sesion_juego),
    CONSTRAINT ck_sesiones_juego_orden_en_ruta CHECK (orden_en_ruta > 0),
    CONSTRAINT ck_sesiones_juego_estrellas_obtenidas CHECK (estrellas_obtenidas >= 0 AND estrellas_obtenidas <= 3),
    CONSTRAINT ck_sesiones_juego_fuente_adaptacion CHECK (fuente_adaptacion::text = ANY (ARRAY['base'::character varying, 'reglas'::character varying, 'ia'::character varying]::text[]))
);

CREATE TABLE IF NOT EXISTS public.tipos_evento
(
    id_tipo_evento integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tipos_evento_pkey PRIMARY KEY (id_tipo_evento),
    CONSTRAINT tipos_evento_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id_usuario integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    contrasena_hash text COLLATE pg_catalog."default" NOT NULL,
    rol_id integer NOT NULL,
    institucion_id integer,
    estado_id integer NOT NULL DEFAULT 1,
    es_admin_principal boolean NOT NULL DEFAULT false,
    creado_en timestamp with time zone NOT NULL DEFAULT now(),
    actualizado_en timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario),
    CONSTRAINT usuarios_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.solicitudes_reactivacion
(
    id_solicitud integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    usuario_id integer NOT NULL,
    correo_contacto character varying(255) COLLATE pg_catalog."default" NOT NULL,
    motivo text COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    estado_solicitud character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pendiente'::character varying,
    respuesta_admin text COLLATE pg_catalog."default",
    leida_admin boolean NOT NULL DEFAULT false,
    fecha_solicitud timestamp without time zone NOT NULL DEFAULT now(),
    fecha_respuesta timestamp without time zone,
    CONSTRAINT solicitudes_reactivacion_pkey PRIMARY KEY (id_solicitud),
    CONSTRAINT chk_estado_solicitud CHECK (estado_solicitud::text = ANY (ARRAY['pendiente'::character varying, 'aprobado'::character varying, 'rechazado'::character varying]::text[])),
    CONSTRAINT chk_respuesta_admin CHECK ((estado_solicitud::text = 'rechazado'::text AND respuesta_admin IS NOT NULL AND respuesta_admin <> ''::text) OR estado_solicitud::text <> 'rechazado'::text),
    CONSTRAINT chk_fecha_respuesta CHECK ((estado_solicitud::text = ANY (ARRAY['aprobado'::character varying, 'rechazado'::character varying]::text[])) AND fecha_respuesta IS NOT NULL OR estado_solicitud::text = 'pendiente'::text),
    CONSTRAINT fk_solicitudes_usuario FOREIGN KEY (usuario_id)
        REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_solicitudes_usuario
    ON public.solicitudes_reactivacion(usuario_id);
CREATE INDEX IF NOT EXISTS idx_solicitudes_estado
    ON public.solicitudes_reactivacion(estado_solicitud);
CREATE INDEX IF NOT EXISTS idx_solicitudes_leida
    ON public.solicitudes_reactivacion(leida_admin);
CREATE INDEX IF NOT EXISTS idx_solicitudes_fecha
    ON public.solicitudes_reactivacion(fecha_solicitud DESC);

ALTER TABLE IF EXISTS public.estadisticas_habilidad
    ADD CONSTRAINT estadisticas_habilidad_estudiante_id_fkey FOREIGN KEY (estudiante_id)
    REFERENCES public.estudiantes (id_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_estadisticas_estudiante
    ON public.estadisticas_habilidad(estudiante_id);


ALTER TABLE IF EXISTS public.estadisticas_habilidad
    ADD CONSTRAINT estadisticas_habilidad_habilidad_id_fkey FOREIGN KEY (habilidad_id)
    REFERENCES public.habilidades (id_habilidad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_estadisticas_habilidad
    ON public.estadisticas_habilidad(habilidad_id);


ALTER TABLE IF EXISTS public.estudiante_grupo_historial
    ADD CONSTRAINT estudiante_grupo_historial_estudiante_id_fkey FOREIGN KEY (estudiante_id)
    REFERENCES public.estudiantes (id_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ux_est_un_grupo_activo
    ON public.estudiante_grupo_historial(estudiante_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_estudiante_un_solo_grupo_activo
    ON public.estudiante_grupo_historial(estudiante_id)
    WHERE activo = true AND fecha_fin IS NULL;


ALTER TABLE IF EXISTS public.estudiante_grupo_historial
    ADD CONSTRAINT estudiante_grupo_historial_grupo_id_fkey FOREIGN KEY (grupo_id)
    REFERENCES public.grupos (id_grupo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_egh_grupo
    ON public.estudiante_grupo_historial(grupo_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_grupo_un_tutor_activo
    ON public.grupo_tutor_historial(grupo_id)
    WHERE activo = true AND fecha_fin IS NULL;
CREATE INDEX IF NOT EXISTS idx_gth_tutor
    ON public.grupo_tutor_historial(tutor_id);
CREATE INDEX IF NOT EXISTS idx_gth_asignado_por
    ON public.grupo_tutor_historial(asignado_por);


ALTER TABLE IF EXISTS public.grupo_tutor_historial
    ADD CONSTRAINT grupo_tutor_historial_grupo_id_fkey FOREIGN KEY (grupo_id)
    REFERENCES public.grupos (id_grupo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.grupo_tutor_historial
    ADD CONSTRAINT grupo_tutor_historial_tutor_id_fkey FOREIGN KEY (tutor_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.grupo_tutor_historial
    ADD CONSTRAINT grupo_tutor_historial_asignado_por_fkey FOREIGN KEY (asignado_por)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.estudiantes
    ADD CONSTRAINT estudiantes_estado_id_fkey FOREIGN KEY (estado_id)
    REFERENCES public.estados_estudiante (id_estado_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_estudiantes_estado
    ON public.estudiantes(estado_id);


ALTER TABLE IF EXISTS public.estudiantes
    ADD CONSTRAINT estudiantes_institucion_id_fkey FOREIGN KEY (institucion_id)
    REFERENCES public.instituciones (id_institucion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.eventos_sesion
    ADD CONSTRAINT eventos_sesion_habilidad_id_fkey FOREIGN KEY (habilidad_id)
    REFERENCES public.habilidades (id_habilidad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_eventos_habilidad
    ON public.eventos_sesion(habilidad_id);


ALTER TABLE IF EXISTS public.eventos_sesion
    ADD CONSTRAINT eventos_sesion_sesion_id_fkey FOREIGN KEY (sesion_id)
    REFERENCES public.sesiones_juego (id_sesion_juego) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_eventos_sesion
    ON public.eventos_sesion(sesion_id);


ALTER TABLE IF EXISTS public.eventos_sesion
    ADD CONSTRAINT eventos_sesion_tipo_evento_id_fkey FOREIGN KEY (tipo_evento_id)
    REFERENCES public.tipos_evento (id_tipo_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_eventos_tipo
    ON public.eventos_sesion(tipo_evento_id);


ALTER TABLE IF EXISTS public.grupos
    ADD CONSTRAINT grupos_institucion_id_fkey FOREIGN KEY (institucion_id)
    REFERENCES public.instituciones (id_institucion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.grupos
    ADD CONSTRAINT grupos_creado_por_usuario_id_fkey FOREIGN KEY (creado_por_usuario_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_grupos_creado_por_usuario
    ON public.grupos(creado_por_usuario_id);
ALTER TABLE IF EXISTS public.grupos
    ADD CONSTRAINT grupos_tutor_asignado_id_fkey FOREIGN KEY (tutor_asignado_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_grupos_tutor_asignado
    ON public.grupos(tutor_asignado_id);
CREATE INDEX IF NOT EXISTS idx_grupos_activo
    ON public.grupos(activo);


ALTER TABLE IF EXISTS public.logros
    ADD CONSTRAINT logros_catalogo_logro_id_fkey FOREIGN KEY (catalogo_logro_id)
    REFERENCES public.catalogo_logros (id_catalogo_logro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_logros_catalogo
    ON public.logros(catalogo_logro_id);


ALTER TABLE IF EXISTS public.logros
    ADD CONSTRAINT logros_estudiante_id_fkey FOREIGN KEY (estudiante_id)
    REFERENCES public.estudiantes (id_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_logros_estudiante
    ON public.logros(estudiante_id);

ALTER TABLE IF EXISTS public.logros
    ADD CONSTRAINT logros_sesion_id_fkey FOREIGN KEY (sesion_id)
    REFERENCES public.sesiones_juego (id_sesion_juego) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_logros_sesion
    ON public.logros(sesion_id);


ALTER TABLE IF EXISTS public.minijuegos
    ADD CONSTRAINT minijuegos_habilidad_id_fkey FOREIGN KEY (habilidad_id)
    REFERENCES public.habilidades (id_habilidad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_minijuegos_habilidad
    ON public.minijuegos(habilidad_id);

CREATE INDEX IF NOT EXISTS idx_minijuegos_catalogo_visible
    ON public.minijuegos(visible_en_catalogo, orden_catalogo);


ALTER TABLE IF EXISTS public.ruta_pedagogica_bloques
    ADD CONSTRAINT ruta_pedagogica_bloques_minijuego_id_fkey FOREIGN KEY (minijuego_id)
    REFERENCES public.minijuegos (id_minijuego) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_ruta_pedagogica_bloques_minijuego
    ON public.ruta_pedagogica_bloques(minijuego_id);

ALTER TABLE IF EXISTS public.ruta_pedagogica_bloques
    ADD CONSTRAINT ruta_pedagogica_bloques_ruta_pedagogica_id_fkey FOREIGN KEY (ruta_pedagogica_id)
    REFERENCES public.rutas_pedagogicas (id_ruta_pedagogica) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ruta_pedagogica_bloques_ruta
    ON public.ruta_pedagogica_bloques(ruta_pedagogica_id);

CREATE INDEX IF NOT EXISTS idx_rutas_pedagogicas_catalogo
    ON public.rutas_pedagogicas(visible_en_catalogo, orden_catalogo);


ALTER TABLE IF EXISTS public.recomendaciones
    ADD CONSTRAINT recomendaciones_estudiante_id_fkey FOREIGN KEY (estudiante_id)
    REFERENCES public.estudiantes (id_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rec_estudiante
    ON public.recomendaciones(estudiante_id);


ALTER TABLE IF EXISTS public.recomendaciones
    ADD CONSTRAINT recomendaciones_grupo_id_fkey FOREIGN KEY (grupo_id)
    REFERENCES public.grupos (id_grupo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rec_grupo
    ON public.recomendaciones(grupo_id);


ALTER TABLE IF EXISTS public.recomendaciones
    ADD CONSTRAINT recomendaciones_habilidad_id_fkey FOREIGN KEY (habilidad_id)
    REFERENCES public.habilidades (id_habilidad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.recomendaciones
    ADD CONSTRAINT recomendaciones_modelo_ia_id_fkey FOREIGN KEY (modelo_ia_id)
    REFERENCES public.modelos_ia (id_modelo_ia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_rec_modelo
    ON public.recomendaciones(modelo_ia_id);


ALTER TABLE IF EXISTS public.recomendaciones
    ADD CONSTRAINT recomendaciones_severidad_id_fkey FOREIGN KEY (severidad_id)
    REFERENCES public.niveles_severidad (id_nivel_severidad) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_rec_severidad
    ON public.recomendaciones(severidad_id);

ALTER TABLE IF EXISTS public.sesiones_clase
    ADD CONSTRAINT sesiones_clase_abierta_por_usuario_id_fkey FOREIGN KEY (abierta_por_usuario_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_sesiones_clase_abierta_por
    ON public.sesiones_clase(abierta_por_usuario_id);

ALTER TABLE IF EXISTS public.sesiones_clase
    ADD CONSTRAINT sesiones_clase_ruta_pedagogica_id_fkey FOREIGN KEY (ruta_pedagogica_id)
    REFERENCES public.rutas_pedagogicas (id_ruta_pedagogica) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_sesiones_clase_ruta_pedagogica
    ON public.sesiones_clase(ruta_pedagogica_id);

ALTER TABLE IF EXISTS public.sesiones_clase
    ADD CONSTRAINT sesiones_clase_grupo_id_fkey FOREIGN KEY (grupo_id)
    REFERENCES public.grupos (id_grupo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sesiones_clase_grupo
    ON public.sesiones_clase(grupo_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_grupo_una_sesion_clase_activa
    ON public.sesiones_clase(grupo_id)
    WHERE estado::text = 'activa'::text;

ALTER TABLE IF EXISTS public.sesiones_clase
    ADD CONSTRAINT sesiones_clase_tutor_responsable_id_fkey FOREIGN KEY (tutor_responsable_id)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_sesiones_clase_tutor
    ON public.sesiones_clase(tutor_responsable_id);

ALTER TABLE IF EXISTS public.sesion_clase_pasos
    ADD CONSTRAINT sesion_clase_pasos_minijuego_id_fkey FOREIGN KEY (minijuego_id)
    REFERENCES public.minijuegos (id_minijuego) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_sesion_clase_pasos_minijuego
    ON public.sesion_clase_pasos(minijuego_id);

ALTER TABLE IF EXISTS public.sesion_clase_pasos
    ADD CONSTRAINT sesion_clase_pasos_sesion_clase_id_fkey FOREIGN KEY (sesion_clase_id)
    REFERENCES public.sesiones_clase (id_sesion_clase) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sesion_clase_pasos_sesion
    ON public.sesion_clase_pasos(sesion_clase_id);

CREATE INDEX IF NOT EXISTS idx_sesion_clase_pasos_bloque
    ON public.sesion_clase_pasos(sesion_clase_id, bloque_orden, nivel_en_bloque);

ALTER TABLE IF EXISTS public.sesion_clase_participantes
    ADD CONSTRAINT sesion_clase_participantes_estudiante_id_fkey FOREIGN KEY (estudiante_id)
    REFERENCES public.estudiantes (id_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sesion_clase_participantes_estudiante
    ON public.sesion_clase_participantes(estudiante_id);

ALTER TABLE IF EXISTS public.sesion_clase_participantes
    ADD CONSTRAINT sesion_clase_participantes_sesion_clase_id_fkey FOREIGN KEY (sesion_clase_id)
    REFERENCES public.sesiones_clase (id_sesion_clase) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sesion_clase_participantes_sesion
    ON public.sesion_clase_participantes(sesion_clase_id);


ALTER TABLE IF EXISTS public.sesiones_juego
    ADD CONSTRAINT sesiones_juego_estado_id_fkey FOREIGN KEY (estado_id)
    REFERENCES public.estados_sesion (id_estado_sesion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_sesiones_estado
    ON public.sesiones_juego(estado_id);


ALTER TABLE IF EXISTS public.sesiones_juego
    ADD CONSTRAINT sesiones_juego_estudiante_id_fkey FOREIGN KEY (estudiante_id)
    REFERENCES public.estudiantes (id_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sesiones_estudiante
    ON public.sesiones_juego(estudiante_id);


ALTER TABLE IF EXISTS public.sesiones_juego
    ADD CONSTRAINT sesiones_juego_minijuego_id_fkey FOREIGN KEY (minijuego_id)
    REFERENCES public.minijuegos (id_minijuego) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_sesiones_minijuego
    ON public.sesiones_juego(minijuego_id);

ALTER TABLE IF EXISTS public.sesiones_juego
    ADD CONSTRAINT sesiones_juego_modelo_ia_id_fkey FOREIGN KEY (modelo_ia_id)
    REFERENCES public.modelos_ia (id_modelo_ia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_sesiones_modelo_ia
    ON public.sesiones_juego(modelo_ia_id);

ALTER TABLE IF EXISTS public.sesiones_juego
    ADD CONSTRAINT sesiones_juego_sesion_clase_id_fkey FOREIGN KEY (sesion_clase_id)
    REFERENCES public.sesiones_clase (id_sesion_clase) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_sesiones_juego_sesion_clase
    ON public.sesiones_juego(sesion_clase_id);

ALTER TABLE IF EXISTS public.sesiones_juego
    ADD CONSTRAINT sesiones_juego_participante_fkey FOREIGN KEY (sesion_clase_id, estudiante_id)
    REFERENCES public.sesion_clase_participantes (sesion_clase_id, estudiante_id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE IF EXISTS public.sesiones_juego
    ADD CONSTRAINT sesiones_juego_paso_fkey FOREIGN KEY (sesion_clase_id, orden_en_ruta)
    REFERENCES public.sesion_clase_pasos (sesion_clase_id, orden)
    DEFERRABLE INITIALLY DEFERRED;


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_estado_id_fkey FOREIGN KEY (estado_id)
    REFERENCES public.estados_usuario (id_estado_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_usuarios_estado
    ON public.usuarios(estado_id);


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_institucion_id_fkey FOREIGN KEY (institucion_id)
    REFERENCES public.instituciones (id_institucion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_usuarios_institucion
    ON public.usuarios(institucion_id);


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_rol_id_fkey FOREIGN KEY (rol_id)
    REFERENCES public.roles (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_usuarios_rol
    ON public.usuarios(rol_id);

END;
